# Generated by Django 4.2 on 2023-04-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceDim',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='sector',
        ),
        migrations.AddField(
            model_name='stock',
            name='sector_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.DeleteModel(
            name='Ticker',
        ),
    ]
