# Generated by Django 4.2 on 2023-05-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_pricedim_remove_ticker_sector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=100)),
                ('sector_growth', models.FloatField(null=True)),
            ],
        ),
    ]
